# .github/workflows/run-server.yml
name: Run Python Server

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run server
      run: |
        nohup python web_version.py &
        sleep 10 # Give the server some time to start
        curl --silent --fail http://localhost:8080/ || exit 1
